services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: wave-web
    ports:
      - "8080:80"
    volumes:
      - ./wave:/var/www/html
    depends_on:
      - db
    restart: "no"

  db:
    image: mysql:8.4
    container_name: wave-db
    restart: "no"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wave_db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wave-phpmyadmin
    restart: "no"
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  wave_db_data:
